# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-11 06:38
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
import django_countries.fields
import django_filepicker.models
import jsonfield.fields
import localflavor.generic.models
import money.contrib.django.models.fields


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='MangoPayBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangopay_id', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=254)),
                ('account_type', models.CharField(choices=[(b'BI', 'BIC & IBAN'), (b'US', 'Local US Format'), (b'O', 'Other')], default=b'BI', max_length=2)),
                ('iban', localflavor.generic.models.IBANField(False, None, blank=True, null=True)),
                ('bic', localflavor.generic.models.BICField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('account_number', models.CharField(blank=True, max_length=15, null=True)),
                ('aba', models.CharField(blank=True, max_length=9, null=True)),
                ('deposit_account_type', models.CharField(blank=True, choices=[(b'CHECKING', 'Checking'), (b'SAVINGS', 'Savings')], max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MangoPayCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangopay_id', models.PositiveIntegerField(blank=True, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=4, null=True)),
                ('alias', models.CharField(blank=True, max_length=16, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_valid', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MangoPayCardRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangopay_id', models.PositiveIntegerField(blank=True, null=True)),
                ('mangopay_card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangopay_card_registration', to='mangopay.MangoPayCard')),
            ],
        ),
        migrations.CreateModel(
            name='MangoPayDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangopay_id', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[(b'IP', b'IDENTITY_PROOF'), (b'RP', b'REGISTRATION_PROOF'), (b'AA', b'ARTICLES_OF_ASSOCIATION'), (b'SD', b'SHAREHOLDER_DECLARATION'), (b'AP', b'ADDRESS_PROOF')], max_length=2)),
                ('status', models.CharField(blank=True, choices=[(b'C', b'CREATED'), (b'A', b'VALIDATION_ASKED'), (b'V', b'VALIDATED'), (b'R', b'REFUSED')], max_length=1, null=True)),
                ('refused_reason_message', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MangoPayPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', django_filepicker.models.FPUrlField(max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangopay_pages', to='mangopay.MangoPayDocument')),
            ],
        ),
        migrations.CreateModel(
            name='MangoPayPayIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangopay_id', models.PositiveIntegerField(blank=True, null=True)),
                ('execution_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[(b'CREATED', 'The request is created but not processed.'), (b'SUCCEEDED', 'The request has been successfully processed.'), (b'FAILED', 'The request has failed.')], max_length=9, null=True)),
                ('debited_funds_currency', money.contrib.django.models.fields.CurrencyField(default=b'EUR', editable=False, max_length=3)),
                ('debited_funds', money.contrib.django.models.fields.MoneyField(decimal_places=2, default=0, max_digits=12, no_currency_field=True)),
                ('fees_currency', money.contrib.django.models.fields.CurrencyField(default=b'EUR', editable=False, max_length=3)),
                ('fees', money.contrib.django.models.fields.MoneyField(decimal_places=2, default=0, max_digits=12, no_currency_field=True)),
                ('result_code', models.CharField(blank=True, max_length=6, null=True)),
                ('type', models.CharField(choices=[(b'bank-wire', 'Pay in by BankWire'), (b'card-web', 'Pay in by card via web')], max_length=10)),
                ('secure_mode_redirect_url', models.URLField(blank=True, null=True)),
                ('wire_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('mangopay_bank_account', jsonfield.fields.JSONField(blank=True, null=True)),
                ('mangopay_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangopay_payins', to='mangopay.MangoPayCard')),
            ],
        ),
        migrations.CreateModel(
            name='MangoPayPayOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangopay_id', models.PositiveIntegerField(blank=True, null=True)),
                ('execution_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[(b'CREATED', 'The request is created but not processed.'), (b'SUCCEEDED', 'The request has been successfully processed.'), (b'FAILED', 'The request has failed.')], max_length=9, null=True)),
                ('debited_funds_currency', money.contrib.django.models.fields.CurrencyField(default=b'EUR', editable=False, max_length=3)),
                ('debited_funds', money.contrib.django.models.fields.MoneyField(decimal_places=2, default=0, max_digits=12, no_currency_field=True)),
                ('fees_currency', money.contrib.django.models.fields.CurrencyField(default=b'EUR', editable=False, max_length=3)),
                ('fees', money.contrib.django.models.fields.MoneyField(decimal_places=2, default=0, max_digits=12, no_currency_field=True)),
                ('mangopay_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangopay_payouts', to='mangopay.MangoPayBankAccount')),
            ],
        ),
        migrations.CreateModel(
            name='MangoPayRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangopay_id', models.PositiveIntegerField(blank=True, null=True)),
                ('execution_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[(b'CREATED', 'The request is created but not processed.'), (b'SUCCEEDED', 'The request has been successfully processed.'), (b'FAILED', 'The request has failed.')], max_length=9, null=True)),
                ('result_code', models.CharField(blank=True, max_length=6, null=True)),
                ('mangopay_pay_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangopay_refunds', to='mangopay.MangoPayPayIn')),
            ],
        ),
        migrations.CreateModel(
            name='MangoPayTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangopay_id', models.PositiveIntegerField(blank=True, null=True)),
                ('debited_funds_currency', money.contrib.django.models.fields.CurrencyField(default=b'EUR', editable=False, max_length=3)),
                ('debited_funds', money.contrib.django.models.fields.MoneyField(decimal_places=2, default=0, max_digits=12, no_currency_field=True)),
                ('execution_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[(b'CREATED', 'The request is created but not processed.'), (b'SUCCEEDED', 'The request has been successfully processed.'), (b'FAILED', 'The request has failed.')], max_length=9, null=True)),
                ('result_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MangoPayUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_edit_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('mangopay_id', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[(b'N', 'Natural User'), (b'B', b'BUSINESS'), (b'O', b'ORGANIZATION')], max_length=1, null=True)),
                ('first_name', models.CharField(blank=True, max_length=99, null=True)),
                ('last_name', models.CharField(blank=True, max_length=99, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('country_of_residence', django_countries.fields.CountryField(max_length=2)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MangoPayWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangopay_id', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default=b'EUR', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MangoPayLegalUser',
            fields=[
                ('mangopayuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mangopay.MangoPayUser')),
                ('business_name', models.CharField(max_length=254)),
                ('generic_business_email', models.EmailField(max_length=254)),
                ('headquaters_address', models.CharField(blank=True, max_length=254, null=True)),
            ],
            bases=('mangopay.mangopayuser',),
        ),
        migrations.CreateModel(
            name='MangoPayNaturalUser',
            fields=[
                ('mangopayuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mangopay.MangoPayUser')),
                ('occupation', models.CharField(blank=True, max_length=254, null=True)),
                ('income_range', models.SmallIntegerField(blank=True, choices=[(1, b'0 - 1,500'), (2, b'1,500 - 2,499'), (3, b'2,500 - 3,999'), (4, b'4,000 - 7,499'), (5, b'7,500 - 9,999'), (6, b'10,000 +')], null=True)),
            ],
            bases=('mangopay.mangopayuser',),
        ),
        migrations.AddField(
            model_name='mangopaywallet',
            name='mangopay_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangopay_wallets', to='mangopay.MangoPayUser'),
        ),
        migrations.AddField(
            model_name='mangopayuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangopay_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mangopaytransfer',
            name='mangopay_credited_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangopay_credited_wallets', to='mangopay.MangoPayWallet'),
        ),
        migrations.AddField(
            model_name='mangopaytransfer',
            name='mangopay_debited_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangopay_debited_wallets', to='mangopay.MangoPayWallet'),
        ),
        migrations.AddField(
            model_name='mangopayrefund',
            name='mangopay_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangopay_refunds', to='mangopay.MangoPayUser'),
        ),
        migrations.AddField(
            model_name='mangopaypayout',
            name='mangopay_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangopay_payouts', to='mangopay.MangoPayUser'),
        ),
        migrations.AddField(
            model_name='mangopaypayout',
            name='mangopay_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangopay_payouts', to='mangopay.MangoPayWallet'),
        ),
        migrations.AddField(
            model_name='mangopaypayin',
            name='mangopay_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangopay_payins', to='mangopay.MangoPayUser'),
        ),
        migrations.AddField(
            model_name='mangopaypayin',
            name='mangopay_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangopay_payins', to='mangopay.MangoPayWallet'),
        ),
        migrations.AddField(
            model_name='mangopaydocument',
            name='mangopay_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangopay_documents', to='mangopay.MangoPayUser'),
        ),
        migrations.AddField(
            model_name='mangopaycardregistration',
            name='mangopay_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangopay_card_registrations', to='mangopay.MangoPayUser'),
        ),
        migrations.AddField(
            model_name='mangopaybankaccount',
            name='mangopay_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangopay_bank_accounts', to='mangopay.MangoPayUser'),
        ),
        migrations.CreateModel(
            name='MangoPayPayInBankWire',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('mangopay.mangopaypayin',),
        ),
        migrations.CreateModel(
            name='MangoPayPayInByCard',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('mangopay.mangopaypayin',),
        ),
    ]
